# Generated by Django 5.1 on 2024-09-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
