# Generated by Django 3.2.25 on 2024-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
