# Generated by Django 4.1.13 on 2024-10-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_alter_review_user_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='things_to_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guide.place'),
        ),
    ]
